# Generated by Django 3.1.2 on 2020-11-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, upload_to='libros/pictures/authores'),
        ),
        migrations.AddField(
            model_name='books',
            name='portada',
            field=models.ImageField(blank=True, upload_to='libros/pictures/books'),
        ),
    ]
