# Generated by Django 3.1.2 on 2020-11-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='id',
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
