# Generated by Django 3.1.2 on 2020-11-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(blank=True, choices=[('Meele', 'Man'), ('Feemele', 'Woman')], max_length=7),
        ),
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='authores/'),
        ),
    ]
