# Generated by Django 3.1.2 on 2020-12-11 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20201125_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='edicion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.editorials'),
        ),
    ]
