# Generated by Django 3.1.2 on 2020-11-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20201119_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, upload_to='authores/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='portada',
            field=models.ImageField(blank=True, upload_to='books/'),
        ),
    ]
