# Generated by Django 3.1.2 on 2020-11-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_auto_20201119_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
    ]
