# Generated by Django 3.1.2 on 2020-11-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_auto_20201120_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='Book',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='Book',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(to='libros.Author'),
        ),
        migrations.AddField(
            model_name='books',
            name='quotes',
            field=models.ManyToManyField(blank=True, to='libros.Quotes'),
        ),
        migrations.AddField(
            model_name='books',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='libros.Reviews'),
        ),
    ]
